import esbuild from 'esbuild';
import { builtinModules } from 'node:module';
import createEsbuildObsidianPlugins from './plugin';

const banner = `/**
 * DO NOT EDIT THIS FILE
 * This file is generated by esbuild-obsidian.
 */
`;

const defaultExternal = [
  'obsidian',
  'electron',
  '@codemirror/autocomplete',
  '@codemirror/collab',
  '@codemirror/commands',
  '@codemirror/language',
  '@codemirror/lint',
  '@codemirror/search',
  '@codemirror/state',
  '@codemirror/view',
  '@lezer/common',
  '@lezer/highlight',
  '@lezer/lr',
  ...builtinModules,
];

const defaultEsbuildConfig = {
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  format: 'cjs',
  target: 'es2022',
} satisfies esbuild.BuildOptions;

export async function createEsbuildObsidianContext({
  esbuildConfig: {
    plugins: userPlugins,
    external: userExternal,
    ...restConfig
  } = {},
  obsidianPluginsConfig,
}: {
  esbuildConfig?: esbuild.BuildOptions;
  obsidianPluginsConfig: Parameters<typeof createEsbuildObsidianPlugins>[0];
}) {
  const external = [...defaultExternal, ...(userExternal ?? [])];

  const plugins: esbuild.Plugin[] = [
    ...createEsbuildObsidianPlugins(obsidianPluginsConfig),
    ...(userPlugins ?? []),
  ];

  const context = await esbuild.context({
    ...defaultEsbuildConfig,
    ...restConfig,
    external,
    plugins,
  });

  return context;
}
